// Final Verified Seed Data for Gyan Sagar Platform
// Target: Ensure every category hits 100 questions.
export const NEPAL_CURATED = [
  // --- LOKSEWA (Nepalese History, Geography, Admin) ---
  { category: 'Loksewa', questionText: "Districts in Nepal?", options: ["75", "76", "77", "78"], correctAnswer: 2, difficulty: "Easy", explanation: "77." },
  { category: 'Loksewa', questionText: "Smallest district?", options: ["Bhaktapur", "Lalitpur", "Kathmandu", "Jhapa"], correctAnswer: 0, difficulty: "Easy", explanation: "Bhaktapur." },
  { category: 'Loksewa', questionText: "First PM of Nepal?", options: ["Bhimsen Thapa", "Jung Bahadur", "Matrika", "Girija"], correctAnswer: 0, difficulty: "Medium", explanation: "Bhimsen Thapa." },
  { category: 'Loksewa', questionText: "Largest lake?", options: ["Rara", "Phewa", "Begnas", "Tilicho"], correctAnswer: 0, difficulty: "Easy", explanation: "Rara." },
  { category: 'Loksewa', questionText: "Deepest river?", options: ["Narayani", "Koshi", "Karnali", "Gandaki"], correctAnswer: 0, difficulty: "Medium", explanation: "Narayani." },
  { category: 'Loksewa', questionText: "Highest waterfall?", options: ["Pachal", "Hyatung", "Rupse", "Tindhare"], correctAnswer: 0, difficulty: "Medium", explanation: "Pachal (381m)." },
  { category: 'Loksewa', questionText: "Birthplace of Buddha?", options: ["Lumbini", "Kapilvastu", "Kushinagar", "Sarnath"], correctAnswer: 0, difficulty: "Easy", explanation: "Lumbini." },
  { category: 'Loksewa', questionText: "Largest district by area?", options: ["Dolpa", "Humla", "Mugu", "Mustang"], correctAnswer: 0, difficulty: "Easy", explanation: "Dolpa." },
  { category: 'Loksewa', questionText: "National bird?", options: ["Danphe", "Munal", "Peacock", "Cuckoo"], correctAnswer: 0, difficulty: "Easy", explanation: "Danphe." },
  { category: 'Loksewa', questionText: "First Nepali lady pilot?", options: ["Rakshya Rana", "Soniya Thapa", "Mira Rai", "None"], correctAnswer: 0, difficulty: "Medium", explanation: "Rakshya Rana." },

  // --- CONSTITUTION ---
  { category: 'Constitution', questionText: "Promulgation date of 2072 Constitution?", options: ["2072 Ashoj 3", "2072 Ashoj 1", "2072 Bhadra 3", "2047 Kartik 23"], correctAnswer: 0, difficulty: "Easy", explanation: "Sept 20, 2015." },
  { category: 'Constitution', questionText: "Total Articles?", options: ["308", "300", "285", "310"], correctAnswer: 0, difficulty: "Easy", explanation: "308." },
  { category: 'Constitution', questionText: "Total Parts?", options: ["35", "30", "33", "25"], correctAnswer: 0, difficulty: "Easy", explanation: "35." },
  { category: 'Constitution', questionText: "Total Schedules?", options: ["9", "7", "5", "10"], correctAnswer: 0, difficulty: "Easy", explanation: "9." },
  { category: 'Constitution', questionText: "Head of government?", options: ["Prime Minister", "President", "King", "Speaker"], correctAnswer: 0, difficulty: "Easy", explanation: "PM." },

  // --- CURRENT AFFAIRS (Final Batch) ---
  { category: 'Current Affairs', questionText: "Who is the current Secretary General of the UN?", options: ["Antonio Guterres", "Ban Ki-moon", "Kofi Annan", "Donald Trump"], correctAnswer: 0, difficulty: "Easy", explanation: "Guterres." },
  { category: 'Current Affairs', questionText: "Winner of ICC Men's T20 World Cup 2024?", options: ["India", "South Africa", "Australia", "Pakistan"], correctAnswer: 0, difficulty: "Easy", explanation: "India." },
  { category: 'Current Affairs', questionText: "Who is the Prime Minister of United Kingdom (2024)?", options: ["Keir Starmer", "Rishi Sunak", "Boris Johnson", "Theresa May"], correctAnswer: 0, difficulty: "Medium", explanation: "Keir Starmer." },
  { category: 'Current Affairs', questionText: "Which movie won Best Picture at Oscars 2024?", options: ["Oppenheimer", "Barbie", "Poor Things", "Killers of the Flower Moon"], correctAnswer: 0, difficulty: "Easy", explanation: "Oppenheimer." },
  { category: 'Current Affairs', questionText: "Who is the current CEO of Twitter (X)?", options: ["Linda Yaccarino", "Elon Musk", "Jack Dorsey", "Parag Agrawal"], correctAnswer: 0, difficulty: "Medium", explanation: "Linda Yaccarino." },
  { category: 'Current Affairs', questionText: "Which country hosted the COP28 climate summit?", options: ["UAE", "Egypt", "UK", "France"], correctAnswer: 0, difficulty: "Medium", explanation: "UAE." },
  { category: 'Current Affairs', questionText: "Who is the current Prime Minister of India?", options: ["Narendra Modi", "Rahul Gandhi", "Amit Shah", "Mamata Banerjee"], correctAnswer: 0, difficulty: "Easy", explanation: "Modi." },
  { category: 'Current Affairs', questionText: "Current President of USA (2024)?", options: ["Joe Biden", "Donald Trump", "Barack Obama", "George Bush"], correctAnswer: 0, difficulty: "Easy", explanation: "Joe Biden." },
  { category: 'Current Affairs', questionText: "Which country launched Aditya-L1 solar mission?", options: ["India", "USA", "China", "Russia"], correctAnswer: 0, difficulty: "Easy", explanation: "India." },
  { category: 'Current Affairs', questionText: "Who won the Ballon d'Or 2023?", options: ["Lionel Messi", "Erling Haaland", "Kylian Mbappe", "Vinicius Jr"], correctAnswer: 0, difficulty: "Easy", explanation: "Messi." },
  { category: 'Current Affairs', questionText: "Winner of IPL 2024?", options: ["KKR", "SRH", "RCB", "MI"], correctAnswer: 0, difficulty: "Easy", explanation: "KKR." },
  { category: 'Current Affairs', questionText: "Who is the current Chancellor of Germany?", options: ["Olaf Scholz", "Angela Merkel", "Gerhard Schroder", "Helmut Kohl"], correctAnswer: 0, difficulty: "Medium", explanation: "Olaf Scholz." },
  { category: 'Current Affairs', questionText: "Which country officially joined NATO as the 32nd member in 2024?", options: ["Sweden", "Finland", "Ukraine", "Poland"], correctAnswer: 0, difficulty: "Medium", explanation: "Sweden." },
  { category: 'Current Affairs', questionText: "Who is the current President of France?", options: ["Emmanuel Macron", "Marine Le Pen", "Nicolas Sarkozy", "Francois Hollande"], correctAnswer: 0, difficulty: "Easy", explanation: "Macron." },
  { category: 'Current Affairs', questionText: "Who is the current CEO of Google?", options: ["Sundar Pichai", "Satya Nadella", "Tim Cook", "Larry Page"], correctAnswer: 0, difficulty: "Easy", explanation: "Sundar Pichai." },
  { category: 'Current Affairs', questionText: "Which city hosted the 2024 Summer Olympics?", options: ["Paris", "Tokyo", "London", "Rio"], correctAnswer: 0, difficulty: "Easy", explanation: "Paris." },
  { category: 'Current Affairs', questionText: "Which AI released GPT-4o?", options: ["OpenAI", "Google", "Meta", "Microsoft"], correctAnswer: 0, difficulty: "Easy", explanation: "OpenAI." },
  { category: 'Current Affairs', questionText: "Current President of Nepal (2024)?", options: ["Ram Chandra Poudel", "Bidya Devi Bhandari", "Ram Baran Yadav", "Nanda Bahadur Pun"], correctAnswer: 0, difficulty: "Easy", explanation: "Poudel." },
  { category: 'Current Affairs', questionText: "Who won the French Open 2024 Men's Singles?", options: ["Carlos Alcaraz", "Novak Djokovic", "Jannik Sinner", "Alexander Zverev"], correctAnswer: 0, difficulty: "Medium", explanation: "Alcaraz." },
  { category: 'Current Affairs', questionText: "Who won the Australian Open 2024 Men's Singles?", options: ["Jannik Sinner", "Daniil Medvedev", "Novak Djokovic", "Carlos Alcaraz"], correctAnswer: 0, difficulty: "Medium", explanation: "Sinner." },
  { category: 'Current Affairs', questionText: "Current Secretary General of SAARC?", options: ["Md. Golam Sarwar", "Esala Weerakoon", "Amjad Sial", "Arjun Thapa"], correctAnswer: 0, difficulty: "Hard", explanation: "Md. Golam Sarwar." },
  { category: 'Current Affairs', questionText: "Who is the Prime Minister of Israel?", options: ["Benjamin Netanyahu", "Yair Lapid", "Naftali Bennett", "Isaac Herzog"], correctAnswer: 0, difficulty: "Easy", explanation: "Netanyahu." },
  { category: 'Current Affairs', questionText: "Which country successfully landed SLIM on the moon in 2024?", options: ["Japan", "India", "USA", "China"], correctAnswer: 0, difficulty: "Medium", explanation: "Japan." },
  { category: 'Current Affairs', questionText: "Which country hosted the 2023 Cricket World Cup?", options: ["India", "England", "Australia", "South Africa"], correctAnswer: 0, difficulty: "Easy", explanation: "India." },
  { category: 'Current Affairs', questionText: "Who is the current Prime Minister of Canada?", options: ["Justin Trudeau", "Stephen Harper", "Pierre Trudeau", "Brian Mulroney"], correctAnswer: 0, difficulty: "Easy", explanation: "Trudeau." },
  { category: 'Current Affairs', questionText: "Current President of the EU Commission?", options: ["Ursula von der Leyen", "Roberta Metsola", "Charles Michel", "Josep Borrell"], correctAnswer: 0, difficulty: "Medium", explanation: "Ursula von der Leyen." },
  { category: 'Current Affairs', questionText: "Who won the Wimbledon 2024 Men's Singles?", options: ["Carlos Alcaraz", "Novak Djokovic", "Jannik Sinner", "Daniil Medvedev"], correctAnswer: 0, difficulty: "Medium", explanation: "Alcaraz." },
  { category: 'Current Affairs', questionText: "Which country is the host of the 2024 G20 Summit?", options: ["Brazil", "India", "South Africa", "USA"], correctAnswer: 0, difficulty: "Medium", explanation: "Brazil." },
  { category: 'Current Affairs', questionText: "Who is the current CEO of Microsoft?", options: ["Satya Nadella", "Bill Gates", "Steve Ballmer", "Tim Cook"], correctAnswer: 0, difficulty: "Easy", explanation: "Satya Nadella." },
  { category: 'Current Affairs', questionText: "Which nation launched the Euclid space telescope in 2023?", options: ["ESA", "NASA", "ISRO", "JAXA"], correctAnswer: 0, difficulty: "Hard", explanation: "European Space Agency." },

  // --- GK (Final Batch) ---
  { category: 'GK', questionText: "Largest desert in Asia?", options: ["Gobi", "Thar", "Sahara", "Arabian"], correctAnswer: 0, difficulty: "Easy", explanation: "Gobi." },
  { category: 'GK', questionText: "Smallest continent?", options: ["Australia", "Europe", "Antarctica", "South America"], correctAnswer: 0, difficulty: "Easy", explanation: "Australia." },
  { category: 'GK', questionText: "Longest wall in the world?", options: ["Great Wall of China", "Berlin Wall", "Western Wall", "Hadrian's Wall"], correctAnswer: 0, difficulty: "Easy", explanation: "Great Wall of China." },
  { category: 'GK', questionText: "Capital of Canada?", options: ["Ottawa", "Toronto", "Vancouver", "Montreal"], correctAnswer: 0, difficulty: "Medium", explanation: "Ottawa." },
  { category: 'GK', questionText: "Which country is known as the Land of white elephants?", options: ["Thailand", "India", "Nepal", "Africa"], correctAnswer: 0, difficulty: "Easy", explanation: "Thailand." },
  { category: 'GK', questionText: "National bird of USA?", options: ["Bald Eagle", "Sparrow", "Hawk", "Eagle"], correctAnswer: 0, difficulty: "Easy", explanation: "Bald Eagle." },
  { category: 'GK', questionText: "Who painted the Mona Lisa?", options: ["Da Vinci", "Picasso", "Van Gogh", "Michelangelo"], correctAnswer: 0, difficulty: "Easy", explanation: "Leonardo da Vinci." },
  { category: 'GK', questionText: "Which is the tallest animal?", options: ["Giraffe", "Elephant", "Camel", "Ostrich"], correctAnswer: 0, difficulty: "Easy", explanation: "Giraffe." },
  { category: 'GK', questionText: "Fastest land animal?", options: ["Cheetah", "Lion", "Leopard", "Tiger"], correctAnswer: 0, difficulty: "Easy", explanation: "Cheetah." },
  { category: 'GK', questionText: "Smallest bird?", options: ["Hummingbird", "Sparrow", "Parrot", "Peacock"], correctAnswer: 0, difficulty: "Easy", explanation: "Bee Hummingbird." },
  { category: 'GK', questionText: "Currency of Japan?", options: ["Yen", "Yuan", "Won", "Dollar"], correctAnswer: 0, difficulty: "Easy", explanation: "Yen." },
  { category: 'GK', questionText: "Currency of UK?", options: ["Pound", "Euro", "Dollar", "Franc"], correctAnswer: 0, difficulty: "Easy", explanation: "Pound Sterling." },
  { category: 'GK', questionText: "Who discovered America?", options: ["Columbus", "Vasco Da Gama", "Cook", "Magellan"], correctAnswer: 0, difficulty: "Easy", explanation: "Columbus." },
  { category: 'GK', questionText: "Largest internal organ?", options: ["Liver", "Brain", "Heart", "Lungs"], correctAnswer: 0, difficulty: "Medium", explanation: "Liver." },
  { category: 'GK', questionText: "Hardest natural substance?", options: ["Diamond", "Gold", "Iron", "Platinum"], correctAnswer: 0, difficulty: "Easy", explanation: "Diamond." },
  { category: 'GK', questionText: "Smallest country in the world?", options: ["Vatican City", "Monaco", "Nauru", "Tuvalu"], correctAnswer: 0, difficulty: "Easy", explanation: "Vatican." },
  { category: 'GK', questionText: "Capital of France?", options: ["Paris", "Lyon", "Nice", "Marseille"], correctAnswer: 0, difficulty: "Easy", explanation: "Paris." },
  { category: 'GK', questionText: "Largest ocean?", options: ["Pacific", "Atlantic", "Indian", "Arctic"], correctAnswer: 0, difficulty: "Easy", explanation: "Pacific." },
  { category: 'GK', questionText: "Red Planet is?", options: ["Mars", "Venus", "Jupiter", "Saturn"], correctAnswer: 0, difficulty: "Easy", explanation: "Mars." },
  { category: 'GK', questionText: "How many continents are there?", options: ["7", "6", "5", "8"], correctAnswer: 0, difficulty: "Easy", explanation: "7." },

  // --- LITERATURE (Final Batch) ---
  { category: 'Literature', questionText: "Author of 'Muna Madan'?", options: ["Laxmi Prasad Devkota", "Bhanubhakta", "Motiram", "Lekhnath"], correctAnswer: 0, difficulty: "Easy", explanation: "Devkota." },
  { category: 'Literature', questionText: "Who wrote 'Hamlet'?", options: ["Shakespeare", "Marlowe", "Milton", "Jonson"], correctAnswer: 0, difficulty: "Easy", explanation: "Shakespeare." },
  { category: 'Literature', questionText: "Who wrote '1984'?", options: ["George Orwell", "Huxley", "Bradbury", "Wells"], correctAnswer: 0, difficulty: "Easy", explanation: "Orwell." },
  { category: 'Literature', questionText: "Who wrote 'The Alchemist'?", options: ["Paulo Coelho", "Dan Brown", "Murakami", "King"], correctAnswer: 0, difficulty: "Easy", explanation: "Paulo Coelho." },
  { category: 'Literature', questionText: "Author of 'China Harayeko Manche'?", options: ["Hari Bansha Acharya", "Madan Krishna", "Rajesh Hamal", "Deepak Raj"], correctAnswer: 0, difficulty: "Easy", explanation: "Hari Bansha Acharya." },
  { category: 'Literature', questionText: "Who wrote 'Jiwan Kanda Ki Phool'?", options: ["Jhamak Ghimire", "Devkota", "Parijat", "Saru Bhakta"], correctAnswer: 0, difficulty: "Easy", explanation: "Jhamak Ghimire." },
  { category: 'Literature', questionText: "Who wrote 'Palpasa Cafe'?", options: ["Narayan Wagle", "Buddhisagar", "Subin Bhattarai", "Amar Neupane"], correctAnswer: 0, difficulty: "Medium", explanation: "Narayan Wagle." },
  { category: 'Literature', questionText: "Who wrote 'Karnali Blues'?", options: ["Buddhisagar", "Narayan Wagle", "Nayan Raj Pandey", "Amar Neupane"], correctAnswer: 0, difficulty: "Medium", explanation: "Buddhisagar." },
  { category: 'Literature', questionText: "Who wrote 'To Kill a Mockingbird'?", options: ["Harper Lee", "Mark Twain", "Hemingway", "Steinbeck"], correctAnswer: 0, difficulty: "Easy", explanation: "Harper Lee." },
  { category: 'Literature', questionText: "Who wrote 'Harry Potter'?", options: ["JK Rowling", "Tolkien", "George RR Martin", "Dan Brown"], correctAnswer: 0, difficulty: "Easy", explanation: "JK Rowling." },
  { category: 'Literature', questionText: "First Nepali novel?", options: ["Roopmati", "Seto Bagh", "Basanti", "Sumnima"], correctAnswer: 0, difficulty: "Hard", explanation: "Roopmati." },
  { category: 'Literature', questionText: "Who wrote 'Seto Bagh'?", options: ["Diamond Shumsher", "BP Koirala", "Parijat", "Devkota"], correctAnswer: 0, difficulty: "Medium", explanation: "Diamond Shumsher." },
  { category: 'Literature', questionText: "Who wrote 'Sumnima'?", options: ["BP Koirala", "Devkota", "Parijat", "Lekhnath"], correctAnswer: 0, difficulty: "Medium", explanation: "BP Koirala." },
  { category: 'Literature', questionText: "Author of 'Pride and Prejudice'?", options: ["Jane Austen", "Charlotte Bronte", "Emily Bronte", "Virginia Woolf"], correctAnswer: 0, difficulty: "Easy", explanation: "Jane Austen." },
  { category: 'Literature', questionText: "Who wrote 'War and Peace'?", options: ["Leo Tolstoy", "Dostoevsky", "Chekhov", "Nabokov"], correctAnswer: 0, difficulty: "Medium", explanation: "Tolstoy." },
  { category: 'Literature', questionText: "Creator of Sherlock Holmes?", options: ["Arthur Conan Doyle", "Agatha Christie", "Edgar Allan Poe", "Ian Fleming"], correctAnswer: 0, difficulty: "Easy", explanation: "Doyle." },
  { category: 'Literature', questionText: "Who wrote 'The Odyssey'?", options: ["Homer", "Virgil", "Sophocles", "Plato"], correctAnswer: 0, difficulty: "Easy", explanation: "Homer." },
  { category: 'Literature', questionText: "Who won Nobel Prize in Literature 2023?", options: ["Jon Fosse", "Annie Ernaux", "Abdulrazak Gurnah", "Louise Gluck"], correctAnswer: 0, difficulty: "Hard", explanation: "Jon Fosse." },
  { category: 'Literature', questionText: "Author of 'A Tale of Two Cities'?", options: ["Charles Dickens", "Thomas Hardy", "Jane Austen", "George Eliot"], correctAnswer: 0, difficulty: "Medium", explanation: "Dickens." },
  { category: 'Literature', questionText: "Who wrote 'Divine Comedy'?", options: ["Dante Alighieri", "Petrarch", "Boccaccio", "Machiavelli"], correctAnswer: 0, difficulty: "Hard", explanation: "Dante." },

  // --- COMPUTER (Final Batch) ---
  { category: 'Computer', questionText: "Full form of RAM?", options: ["Random Access Memory", "Read Access Memory", "Rapid Access Memory", "Real Access Memory"], correctAnswer: 0, difficulty: "Easy", explanation: "RAM." },
  { category: 'Computer', questionText: "Full form of ROM?", options: ["Read Only Memory", "Random Only Memory", "Rapid Only Memory", "Real Only Memory"], correctAnswer: 0, difficulty: "Easy", explanation: "ROM." },
  { category: 'Computer', questionText: "Brain of computer?", options: ["CPU", "RAM", "HDD", "Monitor"], correctAnswer: 0, difficulty: "Easy", explanation: "CPU." },
  { category: 'Computer', questionText: "Father of computer?", options: ["Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs"], correctAnswer: 0, difficulty: "Easy", explanation: "Charles Babbage." },
  { category: 'Computer', questionText: "Full form of HTTP?", options: ["Hypertext Transfer Protocol", "High Transfer Protocol", "Hyperlink Transfer Protocol", "Hyper Transfer Protocol"], correctAnswer: 0, difficulty: "Easy", explanation: "HTTP." },
  { category: 'Computer', questionText: "HTML full form?", options: ["Hypertext Markup Language", "High Text Markup Language", "Hyperlink Text Markup Language", "Hypertext Machine Language"], correctAnswer: 0, difficulty: "Easy", explanation: "HTML." },
  { category: 'Computer', questionText: "1 byte = ?", options: ["8 bits", "4 bits", "16 bits", "32 bits"], correctAnswer: 0, difficulty: "Easy", explanation: "8 bits." },
  { category: 'Computer', questionText: "Primary iPhone OS?", options: ["iOS", "Android", "Windows", "Linux"], correctAnswer: 0, difficulty: "Easy", explanation: "iOS." },
  { category: 'Computer', questionText: "JavaScript extension?", options: [".js", ".py", ".html", ".css"], correctAnswer: 0, difficulty: "Easy", explanation: ".js" },
  { category: 'Computer', questionText: "Full form of CPU?", options: ["Central Processing Unit", "Central Power Unit", "Computer Power Unit", "Control Processing Unit"], correctAnswer: 0, difficulty: "Easy", explanation: "CPU." },
  { category: 'Computer', questionText: "Who founded Microsoft?", options: ["Bill Gates", "Steve Jobs", "Elon Musk", "Zuckerberg"], correctAnswer: 0, difficulty: "Easy", explanation: "Bill Gates." },
  { category: 'Computer', questionText: "Who created Python?", options: ["Guido van Rossum", "James Gosling", "Dennis Ritchie", "Bjarne Stroustrup"], correctAnswer: 0, difficulty: "Medium", explanation: "Guido van Rossum." },
  { category: 'Computer', questionText: "1024 Megabytes = ?", options: ["1 Gigabyte", "1 Terabyte", "1 Kilobyte", "1 Petabyte"], correctAnswer: 0, difficulty: "Easy", explanation: "1 GB." },
  { category: 'Computer', questionText: "Founder of Facebook?", options: ["Mark Zuckerberg", "Jack Dorsey", "Larry Page", "Steve Jobs"], correctAnswer: 0, difficulty: "Easy", explanation: "Zuckerberg." },
  { category: 'Computer', questionText: "What does URL stand for?", options: ["Uniform Resource Locator", "Universal Resource Locator", "Uniform Real Link", "Universal Real Link"], correctAnswer: 0, difficulty: "Medium", explanation: "URL." },
  { category: 'Computer', questionText: "Common port for HTTP?", options: ["80", "443", "21", "22"], correctAnswer: 0, difficulty: "Medium", explanation: "80." },
  { category: 'Computer', questionText: "Common port for HTTPS?", options: ["443", "80", "21", "22"], correctAnswer: 0, difficulty: "Medium", explanation: "443." },
  { category: 'Computer', questionText: "Who founded Apple?", options: ["Steve Jobs", "Bill Gates", "Elon Musk", "Zuckerberg"], correctAnswer: 0, difficulty: "Easy", explanation: "Steve Jobs." },
  { category: 'Computer', questionText: "What does SQL stand for?", options: ["Structured Query Language", "Strong Query Language", "Simple Query Language", "Structured Quick Language"], correctAnswer: 0, difficulty: "Medium", explanation: "SQL." },
  { category: 'Computer', questionText: "Full form of WWW?", options: ["World Wide Web", "World Whole Web", "Wide World Web", "World Web Wide"], correctAnswer: 0, difficulty: "Easy", explanation: "WWW." },

  // --- MATHEMATICS (Final Batch) ---
  { category: 'Mathematics', questionText: "Square of 25?", options: ["625", "225", "425", "525"], correctAnswer: 0, difficulty: "Easy", explanation: "625." },
  { category: 'Mathematics', questionText: "Sum of angles in a triangle?", options: ["180", "90", "360", "270"], correctAnswer: 0, difficulty: "Easy", explanation: "180." },
  { category: 'Mathematics', questionText: "Square root of 144?", options: ["12", "11", "13", "14"], correctAnswer: 0, difficulty: "Easy", explanation: "12." },
  { category: 'Mathematics', questionText: "Binary of 2?", options: ["10", "11", "01", "00"], correctAnswer: 0, difficulty: "Easy", explanation: "10." },
  { category: 'Mathematics', questionText: "Smallest prime number?", options: ["2", "1", "3", "0"], correctAnswer: 0, difficulty: "Easy", explanation: "2." },
  { category: 'Mathematics', questionText: "Sides in Hexagon?", options: ["6", "5", "7", "8"], correctAnswer: 0, difficulty: "Easy", explanation: "6." },
  { category: 'Mathematics', questionText: "7 times 8?", options: ["56", "49", "64", "54"], correctAnswer: 0, difficulty: "Easy", explanation: "56." },
  { category: 'Mathematics', questionText: "2 to the power 5?", options: ["32", "16", "64", "25"], correctAnswer: 0, difficulty: "Medium", explanation: "32." },
  { category: 'Mathematics', questionText: "Cube root of 27?", options: ["3", "9", "2", "4"], correctAnswer: 0, difficulty: "Easy", explanation: "3." },
  { category: 'Mathematics', questionText: "Value of Log 1?", options: ["0", "1", "10", "Infinity"], correctAnswer: 0, difficulty: "Easy", explanation: "0." }
];
